# azure-pipelines.yml

trigger:
- master

variables:
  APP_DIR: '.'

stages:
# ---------- BUILD ----------
- stage: Build
  displayName: Build React app
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: LocalPool
    steps:
    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
        versionSpec: '20.x'

    - script: |
        set -e
        echo "Working dir: $(Build.SourcesDirectory)/$(APP_DIR)"
        cd "$(Build.SourcesDirectory)/$(APP_DIR)"
        npm install
        npm run build
      displayName: npm ci & build

# Detect build output dir and set $(BUILD_OUTPUT_DIR)
    - script: |
        set -e
        CANDIDATES=$(find "$(Build.SourcesDirectory)" -maxdepth 3 -type d \( -name build -o -name dist -o -name out -o -name .next \) | sort)
        if [ -z "$CANDIDATES" ]; then
          echo "##vso[task.logissue type=error]No build output folder found (looked for build, dist, out, .next)."
          exit 1
        fi
        FIRST=$(echo "$CANDIDATES" | head -n1)
        echo "Detected build output: $FIRST"
        echo "##vso[task.setvariable variable=BUILD_OUTPUT_DIR]$FIRST"
      displayName: Detect build output

    - task: PublishPipelineArtifact@1
      displayName: Publish build artifact
      inputs:
        targetPath: '$(BUILD_OUTPUT_DIR)'
        artifact: 'react_build'
        publishLocation: 'pipeline'

# ---------- DEPLOY ----------
- stage: Deploy_Dev
  displayName: Deploy to dev1
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToDev1
    displayName: Deploy to Environment dev1
    environment: dev1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download artifact
            inputs:
              artifact: 'react_build'
              path: '$(Pipeline.Workspace)/react_build'

          - script: |
              set -e
              sudo mkdir -p /var/www/myapp
              rsync -av --delete "$(Pipeline.Workspace)/react_build/" "/var/www/myapp/"
            displayName: Sync files to web root

          - script: |
              if command -v systemctl >/dev/null 2>&1; then
                sudo systemctl reload nginx || sudo systemctl restart nginx
              else
                sudo service nginx reload || sudo service nginx restart
              fi
            displayName: Reload web server
